### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vicn1222** [leoliu0/cik-cusip-mapping#6]
Hi,

Great work! Thanks

I download your codes for test. But it fails.

I modify dl_idx.py so it only download for 2004 as: 

    for year in range(2004, 2005):

It product more than 500,000 lines in full_index.csv. I delete 450,000 lines so it only have about 50,000 filing for test.

I then run "python dl.py 13G 13G", it download all html file in 13G folder, such as 1007853_2004-03-23.html. It doesn't download the form 15G filing. When I run "python parse_cusip.py 13G", it product 13G.csv like below:

13G/2004_02/1000045_2004-02-26.html,,
13G/2004_02/1000097_2004-02-03.html,,
13G/2004_02/1000180_2004-02-13.html,,
13G/2004_02/1000180_2004-02-11.html,,
13G/2004_02/1000209_2004-02-04.html,,
13G/2004_02/1000209_2004-02-12.html,,
13G/2004_02/1000209_2004-02-13.html,,
13G/2004_02/1000227_2004-02-12.html,,
13G/2004_02/1000227_2004-02-13.html,,

There are no cik, cusip. etc...

What do I do wrong?

Thank you!

**Comment by vicn1222** [comment]
Ok,

I delete all the htm in the 13G folder, and manually download 1 filing at https://www.sec.gov/Archives/edgar/data/1759008/000139594221000083/0001395942-21-000083-index.html.

The filing file I download is 
https://www.sec.gov/Archives/edgar/data/1395942/000139594221000083/0001395942-21-000083.txt

I then run "python parse_cusip.py 13G".

The csv output is
13G/2004_01/0001395942-21-000083.txt,0001759008,8096c3403

The cusip is totally wrong. It should be 1142552108

**Comment by leoliu0** [comment]
Thanks for the issue. It seems the example you give has 10 digits cusip which is invalid. 

The script can only takes the best guess of the cusip, so it does not guarantee the 100% accuracy. One should check whether such cusip exists in other database and discard ones non exist.

I will add 9 digit checksum. It only help a little because not many cusips here are 9 digits.

I will check the download script

**Comment by vicn1222** [comment]
This one didn't parse either, which has 9 digits.
https://www.sec.gov/Archives/edgar/data/1337013/000125110921000004/0001251109-21-000004-index.html

**Comment by leoliu0** [comment]
Ya, it is because of HTML. there are just too many junks in HTML tags that messed up the process. However, the program should be able to parse HTML as all the txt are essentially HTML after 2011. I wrote parse_cusip_html.py to have more effort cleaning up HTML. Try that (at least it parses your example file correctly). Currently, I don't have a gauge on the impact of the fix on other files. So this is a separate script. When I have time, I will try the fix on the entire 13G/F universe to see whether it is working properly. If so, this script should replace parse_cusip.py

**Comment by vicn1222** [comment]
Thanks! Excellent works!

**Comment by vicn1222** [comment]
Your regexp doesn't accept bond or preferred stock cusip, such as "90214JAB7". Only last check sum has to be digit. 7-8 position can be letters.

You can see a lot of bond or preferred stock cusip at this 13F filings: https://www.sec.gov/Archives/edgar/data/19617/000001961721000478/xslForm13F_X01/Information_Table_JPMCB.xml

Although it is 13F, but 13G/13D also have those cusip.

**Comment by vicn1222** [comment]
Don't want you to waste time. Those 13D/G are really in random formats....

**Comment by vicn1222** [comment]
Don't want you to waste time. Those 13D/G are really in random formats....

**Comment by leoliu0** [comment]
It’s fine. Please keep feeding examples for me to improve the code if you want. It can only get better. I thank you for helping me make it better
